// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Bonds RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
agg = get_data("AGG")

//assets - Bonds (Anleihen) - TVC Symbols (Yields inverted)
us10y = get_data("TVC:US10Y") * -1
us30y = get_data("TVC:US30Y") * -1
us05y = get_data("TVC:US05Y") * -1
us02y = get_data("TVC:US02Y") * -1
de10y = get_data("TVC:DE10Y") * -1
gb10y = get_data("TVC:GB10Y") * -1
jp10y = get_data("TVC:JP10Y") * -1
fr10y = get_data("TVC:FR10Y") * -1
it10y = get_data("TVC:IT10Y") * -1
es10y = get_data("TVC:ES10Y") * -1
ca10y = get_data("TVC:CA10Y") * -1
au10y = get_data("TVC:AU10Y") * -1
ch10y = get_data("TVC:CH10Y") * -1


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == us10y ? us10y : asset / us10y)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == agg ? agg : asset / agg)),
         nz(L.qqq_4d_cal(asset == us10y ? us10y : asset / us10y)),
         
         nz(L.qqq_4d_cal(asset == us30y ? us30y : asset / us30y)),
         nz(L.qqq_4d_cal(asset == us05y ? us05y : asset / us05y)),
        
         nz(L.qqq_4d_cal(asset == us02y ? us02y : asset / us02y)),
         nz(L.qqq_4d_cal(asset == de10y ? de10y : asset / de10y)),
         nz(L.qqq_4d_cal(asset == gb10y ? gb10y : asset / gb10y)),
         nz(L.qqq_4d_cal(asset == jp10y ? jp10y : asset / jp10y)),
         nz(L.qqq_4d_cal(asset == fr10y ? fr10y : asset / fr10y)),
         nz(L.qqq_4d_cal(asset == it10y ? it10y : asset / it10y)),
         nz(L.qqq_4d_cal(asset == es10y ? es10y : asset / es10y)),
         nz(L.qqq_4d_cal(asset == ca10y ? ca10y : asset / ca10y)),
         nz(L.qqq_4d_cal(asset == au10y ? au10y : asset / au10y)),
         nz(L.qqq_4d_cal(asset == ch10y ? ch10y : asset / ch10y))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//bonds bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//bonds
names = array.from(
     "us10y", "agg",
     "us30y", "us05y", 
     "us02y", "de10y", 
     "gb10y", "jp10y",
     "fr10y", "it10y",
     "es10y", "ca10y", 
     "au10y", "ch10y"
  
     )


values = array.from(

     get_rsps(us10y), get_rsps(agg), 
     get_rsps(us30y), get_rsps(us05y), 
     get_rsps(us02y), get_rsps(de10y), 
     get_rsps(gb10y), get_rsps(jp10y),
     get_rsps(fr10y), get_rsps(it10y), 
     get_rsps(es10y), get_rsps(ca10y), get_rsps(au10y), get_rsps(ch10y)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc
     )

roc_alts = array.from(
     ta.roc(us10y, 1) * alloc.get(0)[1], ta.roc(agg, 1) * alloc.get(1)[1], 
     ta.roc(us30y, 1) * alloc.get(2)[1], ta.roc(us05y, 1) * alloc.get(3)[1], 
     ta.roc(us02y, 1) * alloc.get(4)[1], ta.roc(de10y, 1) * alloc.get(5)[1], 
     ta.roc(gb10y, 1) * alloc.get(6)[1], ta.roc(jp10y, 1) * alloc.get(7)[1],
     ta.roc(fr10y, 1) * alloc.get(8)[1], ta.roc(it10y, 1) * alloc.get(9)[1],
     ta.roc(es10y, 1) * alloc.get(10)[1], ta.roc(ca10y, 1) * alloc.get(11)[1],
     ta.roc(au10y, 1) * alloc.get(12)[1], ta.roc(ch10y, 1) * alloc.get(13)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("AGG * -1"),
         get_data2("TVC:US10Y"),
         get_data2("TVC:US30Y"),
         get_data2("TVC:US05Y"),
         get_data2("TVC:US02Y"),
         get_data2("TVC:DE10Y"),
         get_data2("TVC:GB10Y"),
         get_data2("TVC:JP10Y"),
         get_data2("TVC:FR10Y"),
         get_data2("TVC:IT10Y"),
         get_data2("TVC:ES10Y"),
         get_data2("TVC:CA10Y"),
         get_data2("TVC:AU10Y"),
         get_data2("TVC:CH10Y")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var t = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//bonds header
    t.cell(0, 2, "Bonds", text_color = #ffffff)
    t.merge_cells(0, 2, 2, 2)
    t.cell(0, 3, "Asset", text_color = #ffffff)
    t.cell(1, 3, "RSPS Value", text_color = #ffffff)
    t.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(t, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(t, 2, 3, " ", text_color = #ffffff)




//spacer
    t.cell(0, 1, "                ")
    t.cell(0, 12, "                ")


     //bonds main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 12
        // Asset-Namen anzeigen
        table.cell(t, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(t, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(t, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(t, 0, 17, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(t, 1, 17, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(t, 2, 17, str.tostring(the_cash_plot), text_color = color.blue)
