// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Communication Services RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
xlc = get_data("XLC")

//assets - Communication Services (Telekommunikation)
meta = get_data("META")
googl = get_data("GOOGL")
nflx = get_data("NFLX")
dis = get_data("DIS")
cmcsa = get_data("CMCSA")
t = get_data("T")
vz = get_data("VZ")
tmus = get_data("TMUS")
chtr = get_data("CHTR")
ea = get_data("EA")
ttwo = get_data("TTWO")
snap = get_data("SNAP")
mtch = get_data("MTCH")


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == meta ? meta : asset / meta)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == xlc ? xlc : asset / xlc)),
         nz(L.qqq_4d_cal(asset == meta ? meta : asset / meta)),
         
         nz(L.qqq_4d_cal(asset == googl ? googl : asset / googl)),
         nz(L.qqq_4d_cal(asset == nflx ? nflx : asset / nflx)),
        
         nz(L.qqq_4d_cal(asset == dis ? dis : asset / dis)),
         nz(L.qqq_4d_cal(asset == cmcsa ? cmcsa : asset / cmcsa)),
         nz(L.qqq_4d_cal(asset == t ? t : asset / t)),
         nz(L.qqq_4d_cal(asset == vz ? vz : asset / vz)),
         nz(L.qqq_4d_cal(asset == tmus ? tmus : asset / tmus)),
         nz(L.qqq_4d_cal(asset == chtr ? chtr : asset / chtr)),
         nz(L.qqq_4d_cal(asset == ea ? ea : asset / ea)),
         nz(L.qqq_4d_cal(asset == ttwo ? ttwo : asset / ttwo)),
         nz(L.qqq_4d_cal(asset == snap ? snap : asset / snap)),
         nz(L.qqq_4d_cal(asset == mtch ? mtch : asset / mtch))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//xlc bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//xlc
names = array.from(
     "meta", "xlc",
     "googl", "nflx", 
     "dis", "cmcsa", 
     "t", "vz",
     "tmus", "chtr",
     "ea", "ttwo", 
     "snap", "mtch"
  
     )


values = array.from(

     get_rsps(meta), get_rsps(xlc), 
     get_rsps(googl), get_rsps(nflx), 
     get_rsps(dis), get_rsps(cmcsa), 
     get_rsps(t), get_rsps(vz),
     get_rsps(tmus), get_rsps(chtr), 
     get_rsps(ea), get_rsps(ttwo), get_rsps(snap), get_rsps(mtch)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc
     )

roc_alts = array.from(
     ta.roc(meta, 1) * alloc.get(0)[1], ta.roc(xlc, 1) * alloc.get(1)[1], 
     ta.roc(googl, 1) * alloc.get(2)[1], ta.roc(nflx, 1) * alloc.get(3)[1], 
     ta.roc(dis, 1) * alloc.get(4)[1], ta.roc(cmcsa, 1) * alloc.get(5)[1], 
     ta.roc(t, 1) * alloc.get(6)[1], ta.roc(vz, 1) * alloc.get(7)[1],
     ta.roc(tmus, 1) * alloc.get(8)[1], ta.roc(chtr, 1) * alloc.get(9)[1],
     ta.roc(ea, 1) * alloc.get(10)[1], ta.roc(ttwo, 1) * alloc.get(11)[1],
     ta.roc(snap, 1) * alloc.get(12)[1], ta.roc(mtch, 1) * alloc.get(13)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("XLC * -1"),
         get_data2("META * -1"),
         get_data2("GOOGL * -1"),
         get_data2("NFLX * -1"),
         get_data2("DIS * -1"),
         get_data2("CMCSA * -1"),
         get_data2("T * -1"),
         get_data2("VZ * -1"),
         get_data2("TMUS * -1"),
         get_data2("CHTR * -1"),
         get_data2("EA * -1"),
         get_data2("TTWO * -1"),
         get_data2("SNAP * -1"),
         get_data2("MTCH * -1")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var comm_table = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//xlc header
    comm_table.cell(0, 2, "Communication", text_color = #ffffff)
    comm_table.merge_cells(0, 2, 2, 2)
    comm_table.cell(0, 3, "Asset", text_color = #ffffff)
    comm_table.cell(1, 3, "RSPS Value", text_color = #ffffff)
    comm_table.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(comm_table, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(comm_table, 2, 3, " ", text_color = #ffffff)




//spacer
    comm_table.cell(0, 1, "                ")
    comm_table.cell(0, 12, "                ")


     //xlc main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 12
        // Asset-Namen anzeigen
        table.cell(comm_table, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(comm_table, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(comm_table, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(comm_table, 0, 17, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(comm_table, 1, 17, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(comm_table, 2, 17, str.tostring(the_cash_plot), text_color = color.blue)
