// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Financials RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
xlf = get_data("XLF")

//assets - Financials (Finanzdienstleister)
brk_b = get_data("BRK.B")
jpm = get_data("JPM")
bac = get_data("BAC")
wfc = get_data("WFC")
ms = get_data("MS")
gs = get_data("GS")
axp = get_data("AXP")
c = get_data("C")
schw = get_data("SCHW")
cb = get_data("CB")
blk = get_data("BLK")
spgi = get_data("SPGI")
aig = get_data("AIG")


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == brk_b ? brk_b : asset / brk_b)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == xlf ? xlf : asset / xlf)),
         nz(L.qqq_4d_cal(asset == brk_b ? brk_b : asset / brk_b)),
         
         nz(L.qqq_4d_cal(asset == jpm ? jpm : asset / jpm)),
         nz(L.qqq_4d_cal(asset == bac ? bac : asset / bac)),
        
         nz(L.qqq_4d_cal(asset == wfc ? wfc : asset / wfc)),
         nz(L.qqq_4d_cal(asset == ms ? ms : asset / ms)),
         nz(L.qqq_4d_cal(asset == gs ? gs : asset / gs)),
         nz(L.qqq_4d_cal(asset == axp ? axp : asset / axp)),
         nz(L.qqq_4d_cal(asset == c ? c : asset / c)),
         nz(L.qqq_4d_cal(asset == schw ? schw : asset / schw)),
         nz(L.qqq_4d_cal(asset == cb ? cb : asset / cb)),
         nz(L.qqq_4d_cal(asset == blk ? blk : asset / blk)),
         nz(L.qqq_4d_cal(asset == spgi ? spgi : asset / spgi)),
         nz(L.qqq_4d_cal(asset == aig ? aig : asset / aig))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//xlf bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//xlf
names = array.from(
     "brk.b", "xlf",
     "jpm", "bac", 
     "wfc", "ms", 
     "gs", "axp",
     "c", "schw",
     "cb", "blk", 
     "spgi", "aig"
  
     )


values = array.from(

     get_rsps(brk_b), get_rsps(xlf), 
     get_rsps(jpm), get_rsps(bac), 
     get_rsps(wfc), get_rsps(ms), 
     get_rsps(gs), get_rsps(axp),
     get_rsps(c), get_rsps(schw), 
     get_rsps(cb), get_rsps(blk), get_rsps(spgi), get_rsps(aig)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc
     )

roc_alts = array.from(
     ta.roc(brk_b, 1) * alloc.get(0)[1], ta.roc(xlf, 1) * alloc.get(1)[1], 
     ta.roc(jpm, 1) * alloc.get(2)[1], ta.roc(bac, 1) * alloc.get(3)[1], 
     ta.roc(wfc, 1) * alloc.get(4)[1], ta.roc(ms, 1) * alloc.get(5)[1], 
     ta.roc(gs, 1) * alloc.get(6)[1], ta.roc(axp, 1) * alloc.get(7)[1],
     ta.roc(c, 1) * alloc.get(8)[1], ta.roc(schw, 1) * alloc.get(9)[1],
     ta.roc(cb, 1) * alloc.get(10)[1], ta.roc(blk, 1) * alloc.get(11)[1],
     ta.roc(spgi, 1) * alloc.get(12)[1], ta.roc(aig, 1) * alloc.get(13)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("XLF * -1"),
         get_data2("BRK.B * -1"),
         get_data2("JPM * -1"),
         get_data2("BAC * -1"),
         get_data2("WFC * -1"),
         get_data2("MS * -1"),
         get_data2("GS * -1"),
         get_data2("AXP * -1"),
         get_data2("C * -1"),
         get_data2("SCHW * -1"),
         get_data2("CB * -1"),
         get_data2("BLK * -1"),
         get_data2("SPGI * -1"),
         get_data2("AIG * -1")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var t = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//xlf header
    t.cell(0, 2, "Financials", text_color = #ffffff)
    t.merge_cells(0, 2, 2, 2)
    t.cell(0, 3, "Asset", text_color = #ffffff)
    t.cell(1, 3, "RSPS Value", text_color = #ffffff)
    t.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(t, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(t, 2, 3, " ", text_color = #ffffff)




//spacer
    t.cell(0, 1, "                ")
    t.cell(0, 12, "                ")


     //xlf main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 12
        // Asset-Namen anzeigen
        table.cell(t, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(t, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(t, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(t, 0, 17, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(t, 1, 17, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(t, 2, 17, str.tostring(the_cash_plot), text_color = color.blue)
