// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Memecoins RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)

//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
btc = get_data("BINANCE:BTCUSDT")

//assets - Memecoins
doge = get_data("BINANCE:DOGEUSDT")
shib = get_data("BINANCE:SHIBUSDT")
pepe = get_data("BINANCE:PEPEUSDT")
floki = get_data("BINANCE:FLOKIUSDT")
bonk = get_data("BINANCE:BONKUSDT")
wif = get_data("BINANCE:WIFUSDT")
meme = get_data("BINANCE:MEMEUSDT")
bome = get_data("BINANCE:BOMEUSDT")
mog = get_data("MEXC:MOGUSDT")
popcat = get_data("MEXC:POPCATUSDT")
brett = get_data("MEXC:BRETTUSDT")
turbo = get_data("BINANCE:TURBOUSDT")
neiro = get_data("BINANCE:NEIROUSDT")
mew = get_data("MEXC:MEWUSDT")
giga = get_data("MEXC:GIGAUSDT")
ponke = get_data("MEXC:PONKEUSDT")
billy = get_data("MEXC:BILLYUSDT")
myro = get_data("MEXC:MYROUSDT")
degen = get_data("MEXC:DEGENUSDT")


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == doge ? doge : asset / doge)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == btc ? btc : asset / btc)),
         nz(L.qqq_4d_cal(asset == doge ? doge : asset / doge)),
         
         nz(L.qqq_4d_cal(asset == shib ? shib : asset / shib)),
         nz(L.qqq_4d_cal(asset == pepe ? pepe : asset / pepe)),
        
         nz(L.qqq_4d_cal(asset == floki ? floki : asset / floki)),
         nz(L.qqq_4d_cal(asset == bonk ? bonk : asset / bonk)),
         nz(L.qqq_4d_cal(asset == wif ? wif : asset / wif)),
         nz(L.qqq_4d_cal(asset == meme ? meme : asset / meme)),
         nz(L.qqq_4d_cal(asset == bome ? bome : asset / bome)),
         nz(L.qqq_4d_cal(asset == mog ? mog : asset / mog)),
         nz(L.qqq_4d_cal(asset == popcat ? popcat : asset / popcat)),
         nz(L.qqq_4d_cal(asset == brett ? brett : asset / brett)),
         nz(L.qqq_4d_cal(asset == turbo ? turbo : asset / turbo)),
         nz(L.qqq_4d_cal(asset == neiro ? neiro : asset / neiro)),
         nz(L.qqq_4d_cal(asset == mew ? mew : asset / mew)),
         nz(L.qqq_4d_cal(asset == giga ? giga : asset / giga)),
         nz(L.qqq_4d_cal(asset == ponke ? ponke : asset / ponke)),
         nz(L.qqq_4d_cal(asset == billy ? billy : asset / billy)),
         nz(L.qqq_4d_cal(asset == myro ? myro : asset / myro)),
         nz(L.qqq_4d_cal(asset == degen ? degen : asset / degen))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

names = array.from(
     "doge", "btc",
     "shib", "pepe", 
     "floki", "bonk", 
     "wif", "meme",
     "bome", "mog",
     "popcat", "brett", 
     "turbo", "neiro", "mew",
     "giga", "ponke", "billy",
     "myro", "degen"
  
     )


values = array.from(

     get_rsps(doge), get_rsps(btc), 
     get_rsps(shib), get_rsps(pepe), 
     get_rsps(floki), get_rsps(bonk), 
     get_rsps(wif), get_rsps(meme),
     get_rsps(bome), get_rsps(mog), 
     get_rsps(popcat), get_rsps(brett), get_rsps(turbo), get_rsps(neiro), get_rsps(mew),
     get_rsps(giga), get_rsps(ponke), get_rsps(billy), get_rsps(myro), get_rsps(degen)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13)), filter(values.get(14)),
     filter(values.get(15)), filter(values.get(16)), filter(values.get(17)), filter(values.get(18)),
     filter(values.get(19))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc, filtered_values.get(14) / max_alloc,
     filtered_values.get(15) / max_alloc, filtered_values.get(16) / max_alloc,
     filtered_values.get(17) / max_alloc, filtered_values.get(18) / max_alloc,
     filtered_values.get(19) / max_alloc
     )

roc_alts = array.from(
     ta.roc(doge, 1) * alloc.get(0)[1], ta.roc(btc, 1) * alloc.get(1)[1], 
     ta.roc(shib, 1) * alloc.get(2)[1], ta.roc(pepe, 1) * alloc.get(3)[1], 
     ta.roc(floki, 1) * alloc.get(4)[1], ta.roc(bonk, 1) * alloc.get(5)[1], 
     ta.roc(wif, 1) * alloc.get(6)[1], ta.roc(meme, 1) * alloc.get(7)[1],
     ta.roc(bome, 1) * alloc.get(8)[1], ta.roc(mog, 1) * alloc.get(9)[1],
     ta.roc(popcat, 1) * alloc.get(10)[1], ta.roc(brett, 1) * alloc.get(11)[1],
     ta.roc(turbo, 1) * alloc.get(12)[1], ta.roc(neiro, 1) * alloc.get(13)[1], ta.roc(mew, 1) * alloc.get(14)[1],
     ta.roc(giga, 1) * alloc.get(15)[1], ta.roc(ponke, 1) * alloc.get(16)[1], ta.roc(billy, 1) * alloc.get(17)[1],
     ta.roc(myro, 1) * alloc.get(18)[1], ta.roc(degen, 1) * alloc.get(19)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         nz(L.deep_1d_cal(btc * -1)),
         nz(L.deep_1d_cal(doge * -1)),
         nz(L.deep_1d_cal(shib * -1)),
         nz(L.deep_1d_cal(pepe * -1)),
         nz(L.deep_1d_cal(floki * -1)),
         nz(L.deep_1d_cal(bonk * -1)),
         nz(L.deep_1d_cal(wif * -1)),
         nz(L.deep_1d_cal(meme * -1)),
         nz(L.deep_1d_cal(bome * -1)),
         nz(L.deep_1d_cal(mog * -1)),
         nz(L.deep_1d_cal(popcat * -1)),
         nz(L.deep_1d_cal(brett * -1)),
         nz(L.deep_1d_cal(turbo * -1)),
         nz(L.deep_1d_cal(neiro * -1)),
         nz(L.deep_1d_cal(mew * -1)),
         nz(L.deep_1d_cal(giga * -1)),
         nz(L.deep_1d_cal(ponke * -1)),
         nz(L.deep_1d_cal(billy * -1)),
         nz(L.deep_1d_cal(myro * -1)),
         nz(L.deep_1d_cal(degen * -1))) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var meme_table = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//header
    meme_table.cell(0, 2, "Memecoins", text_color = #ffffff)
    meme_table.merge_cells(0, 2, 2, 2)
    meme_table.cell(0, 3, "Asset", text_color = #ffffff)
    meme_table.cell(1, 3, "RSPS Value", text_color = #ffffff)
    meme_table.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(meme_table, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(meme_table, 2, 3, " ", text_color = #ffffff)




//spacer
    meme_table.cell(0, 1, "                ")
    meme_table.cell(0, 12, "                ")


     //main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 18
        // Asset-Namen anzeigen
        table.cell(meme_table, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(meme_table, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(meme_table, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(meme_table, 0, 23, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(meme_table, 1, 23, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(meme_table, 2, 23, str.tostring(the_cash_plot), text_color = color.blue)
