// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Technology Stocks RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
xlk = get_data("XLK")

//assets - Technology
aapl = get_data("AAPL")
msft = get_data("MSFT")
nvda = get_data("NVDA")
avgo = get_data("AVGO")
crm = get_data("CRM")
orcl = get_data("ORCL")
csco = get_data("CSCO")
adbe = get_data("ADBE")
acn = get_data("ACN")
amd = get_data("AMD")
ibm = get_data("IBM")
intc = get_data("INTC")
now = get_data("NOW")
txn = get_data("TXN")


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == aapl ? aapl : asset / aapl)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == xlk ? xlk : asset / xlk)),
         nz(L.qqq_4d_cal(asset == aapl ? aapl : asset / aapl)),
         
         nz(L.qqq_4d_cal(asset == msft ? msft : asset / msft)),
         nz(L.qqq_4d_cal(asset == nvda ? nvda : asset / nvda)),
        
         nz(L.qqq_4d_cal(asset == avgo ? avgo : asset / avgo)),
         nz(L.qqq_4d_cal(asset == crm ? crm : asset / crm)),
         nz(L.qqq_4d_cal(asset == orcl ? orcl : asset / orcl)),
         nz(L.qqq_4d_cal(asset == csco ? csco : asset / csco)),
         nz(L.qqq_4d_cal(asset == adbe ? adbe : asset / adbe)),
         nz(L.qqq_4d_cal(asset == acn ? acn : asset / acn)),
         nz(L.qqq_4d_cal(asset == amd ? amd : asset / amd)),
         nz(L.qqq_4d_cal(asset == ibm ? ibm : asset / ibm)),
         nz(L.qqq_4d_cal(asset == intc ? intc : asset / intc)),
         nz(L.qqq_4d_cal(asset == now ? now : asset / now)),
         nz(L.qqq_4d_cal(asset == txn ? txn : asset / txn))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//xlk bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//xlk
names = array.from(
     "aapl", "xlk",
     "msft", "nvda", 
     "avgo", "crm", 
     "orcl", "csco",
     "adbe", "acn",
     "amd", "ibm", 
     "intc", "now", "txn"
  
     )


values = array.from(

     get_rsps(aapl), get_rsps(xlk), 
     get_rsps(msft), get_rsps(nvda), 
     get_rsps(avgo), get_rsps(crm), 
     get_rsps(orcl), get_rsps(csco),
     get_rsps(adbe), get_rsps(acn), 
     get_rsps(amd), get_rsps(ibm), get_rsps(intc), get_rsps(now), get_rsps(txn)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13)), filter(values.get(14))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc, filtered_values.get(14) / max_alloc
     )

roc_alts = array.from(
     ta.roc(aapl, 1) * alloc.get(0)[1], ta.roc(xlk, 1) * alloc.get(1)[1], 
     ta.roc(msft, 1) * alloc.get(2)[1], ta.roc(nvda, 1) * alloc.get(3)[1], 
     ta.roc(avgo, 1) * alloc.get(4)[1], ta.roc(crm, 1) * alloc.get(5)[1], 
     ta.roc(orcl, 1) * alloc.get(6)[1], ta.roc(csco, 1) * alloc.get(7)[1],
     ta.roc(adbe, 1) * alloc.get(8)[1], ta.roc(acn, 1) * alloc.get(9)[1],
     ta.roc(amd, 1) * alloc.get(10)[1], ta.roc(ibm, 1) * alloc.get(11)[1],
     ta.roc(intc, 1) * alloc.get(12)[1], ta.roc(now, 1) * alloc.get(13)[1], ta.roc(txn, 1) * alloc.get(14)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("XLK * -1"),
         get_data2("AAPL * -1"),
         get_data2("MSFT * -1"),
         get_data2("NVDA * -1"),
         get_data2("AVGO * -1"),
         get_data2("CRM * -1"),
         get_data2("ORCL * -1"),
         get_data2("CSCO * -1"),
         get_data2("ADBE * -1"),
         get_data2("ACN * -1"),
         get_data2("AMD * -1"),
         get_data2("IBM * -1"),
         get_data2("INTC * -1"),
         get_data2("NOW * -1"),
         get_data2("TXN * -1")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var t = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//xlk header
    t.cell(0, 2, "Technology", text_color = #ffffff)
    t.merge_cells(0, 2, 2, 2)
    t.cell(0, 3, "Asset", text_color = #ffffff)
    t.cell(1, 3, "RSPS Value", text_color = #ffffff)
    t.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(t, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(t, 2, 3, " ", text_color = #ffffff)




//spacer
    t.cell(0, 1, "                ")
    t.cell(0, 12, "                ")


     //xlk main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 13
        // Asset-Namen anzeigen
        table.cell(t, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(t, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(t, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(t, 0, 18, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(t, 1, 18, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(t, 2, 18, str.tostring(the_cash_plot), text_color = color.blue)
