// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Consumer Staples RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
xlp = get_data("XLP")

//assets - Consumer Staples (Basiskonsumgüter)
pg = get_data("PG")
ko = get_data("KO")
pep = get_data("PEP")
cost = get_data("COST")
wmt = get_data("WMT")
pm = get_data("PM")
mo = get_data("MO")
mdlz = get_data("MDLZ")
cl = get_data("CL")
kvue = get_data("KVUE")
el = get_data("EL")
gis = get_data("GIS")
k = get_data("K")


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == pg ? pg : asset / pg)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == xlp ? xlp : asset / xlp)),
         nz(L.qqq_4d_cal(asset == pg ? pg : asset / pg)),
         
         nz(L.qqq_4d_cal(asset == ko ? ko : asset / ko)),
         nz(L.qqq_4d_cal(asset == pep ? pep : asset / pep)),
        
         nz(L.qqq_4d_cal(asset == cost ? cost : asset / cost)),
         nz(L.qqq_4d_cal(asset == wmt ? wmt : asset / wmt)),
         nz(L.qqq_4d_cal(asset == pm ? pm : asset / pm)),
         nz(L.qqq_4d_cal(asset == mo ? mo : asset / mo)),
         nz(L.qqq_4d_cal(asset == mdlz ? mdlz : asset / mdlz)),
         nz(L.qqq_4d_cal(asset == cl ? cl : asset / cl)),
         nz(L.qqq_4d_cal(asset == kvue ? kvue : asset / kvue)),
         nz(L.qqq_4d_cal(asset == el ? el : asset / el)),
         nz(L.qqq_4d_cal(asset == gis ? gis : asset / gis)),
         nz(L.qqq_4d_cal(asset == k ? k : asset / k))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//xlp bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//xlp
names = array.from(
     "pg", "xlp",
     "ko", "pep", 
     "cost", "wmt", 
     "pm", "mo",
     "mdlz", "cl",
     "kvue", "el", 
     "gis", "k"
  
     )


values = array.from(

     get_rsps(pg), get_rsps(xlp), 
     get_rsps(ko), get_rsps(pep), 
     get_rsps(cost), get_rsps(wmt), 
     get_rsps(pm), get_rsps(mo),
     get_rsps(mdlz), get_rsps(cl), 
     get_rsps(kvue), get_rsps(el), get_rsps(gis), get_rsps(k)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), filter(values.get(8)), 
     filter(values.get(9)), filter(values.get(10)),
     filter(values.get(11)), filter(values.get(12)), filter(values.get(13))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, filtered_values.get(8) / max_alloc, 
     filtered_values.get(9) / max_alloc, filtered_values.get(10) / max_alloc,
     filtered_values.get(11) / max_alloc, filtered_values.get(12) / max_alloc, 
     filtered_values.get(13) / max_alloc
     )

roc_alts = array.from(
     ta.roc(pg, 1) * alloc.get(0)[1], ta.roc(xlp, 1) * alloc.get(1)[1], 
     ta.roc(ko, 1) * alloc.get(2)[1], ta.roc(pep, 1) * alloc.get(3)[1], 
     ta.roc(cost, 1) * alloc.get(4)[1], ta.roc(wmt, 1) * alloc.get(5)[1], 
     ta.roc(pm, 1) * alloc.get(6)[1], ta.roc(mo, 1) * alloc.get(7)[1],
     ta.roc(mdlz, 1) * alloc.get(8)[1], ta.roc(cl, 1) * alloc.get(9)[1],
     ta.roc(kvue, 1) * alloc.get(10)[1], ta.roc(el, 1) * alloc.get(11)[1],
     ta.roc(gis, 1) * alloc.get(12)[1], ta.roc(k, 1) * alloc.get(13)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("XLP * -1"),
         get_data2("PG * -1"),
         get_data2("KO * -1"),
         get_data2("PEP * -1"),
         get_data2("COST * -1"),
         get_data2("WMT * -1"),
         get_data2("PM * -1"),
         get_data2("MO * -1"),
         get_data2("MDLZ * -1"),
         get_data2("CL * -1"),
         get_data2("KVUE * -1"),
         get_data2("EL * -1"),
         get_data2("GIS * -1"),
         get_data2("K * -1")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

majors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(majors_strength, "Majors tpi", color, 3)
fill(f1, f2, color)


col_out = majors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + majors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = majors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_alts.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= majors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var t = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//xlp header
    t.cell(0, 2, "Consumer Staples", text_color = #ffffff)
    t.merge_cells(0, 2, 2, 2)
    t.cell(0, 3, "Asset", text_color = #ffffff)
    t.cell(1, 3, "RSPS Value", text_color = #ffffff)
    t.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(t, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(t, 2, 3, " ", text_color = #ffffff)




//spacer
    t.cell(0, 1, "                ")
    t.cell(0, 12, "                ")


     //xlp main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 12
        // Asset-Namen anzeigen
        table.cell(t, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(t, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(t, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(t, 0, 17, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(t, 1, 17, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(t, 2, 17, str.tostring(the_cash_plot), text_color = color.blue)
