// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © unicorpusstocks

// note:
// I especially don't use for-loops in this file, due to it getting to unprecise. 
// Everything is calculated semi-individual to reduce errors and noise



//@version=5
indicator("Sector RSPS", max_bars_back = 100)


import Unicorpus/NormalizedIndicators/1 as L


//Getting values
get_data(string input) =>
    request.security(input, timeframe.period, close)


//Symbols

//benchmark
usdt = get_data("CRYPTO:USDTUSD")
spy = get_data("SPY")

//sectors
xlk = get_data("XLK")  // Technologie
xlc = get_data("XLC")  // Telekommunikation
xlv = get_data("XLV")  // Gesundheitswesen
xlf = get_data("XLF")  // Finanzdienstleister
xly = get_data("XLY")  // Verbrauchsgüter
xlp = get_data("XLP")  // Basiskonsumgüter
xli = get_data("XLI")  // Industrieunternehmen
xlb = get_data("XLB")  // Grundstoffe
xle = get_data("XLE")  // Energie
xlu = get_data("XLU")  // Versorgungsunternehmen


//======================================================



get_rsps(asset) =>

    math.avg(nz(L.qqq_4d_cal(asset == xlk ? xlk : asset / xlk)), nz(L.qqq_4d_cal(asset))) <= 0.1 ? -0.5 : math.avg(

        
         nz(L.qqq_4d_cal(asset == spy ? spy : asset / spy)),
         nz(L.qqq_4d_cal(asset == xlk ? xlk : asset / xlk)),
         
         nz(L.qqq_4d_cal(asset == xlc ? xlc : asset / xlc)),
         nz(L.qqq_4d_cal(asset == xlv ? xlv : asset / xlv)),
        
         nz(L.qqq_4d_cal(asset == xlf ? xlf : asset / xlf)),
         nz(L.qqq_4d_cal(asset == xly ? xly : asset / xly)),
         nz(L.qqq_4d_cal(asset == xlp ? xlp : asset / xlp)),
         nz(L.qqq_4d_cal(asset == xli ? xli : asset / xli)),
         nz(L.qqq_4d_cal(asset == xlb ? xlb : asset / xlb)),
         nz(L.qqq_4d_cal(asset == xle ? xle : asset / xle)),
         nz(L.qqq_4d_cal(asset == xlu ? xlu : asset / xlu))
         )
      
filter(input)=>
     input >= 0 ? input : 0

//======================================================
//sector bools
plot_table = input.bool(true)

//=======================================================
//declaring arrays for tables

//sectors
names = array.from(
     "xlk", "xlc",
     "xlv", "xlf", 
     "xly", "xlp", 
     "xli", "xlb",
     "xle", "xlu",
     "spy"
     )


values = array.from(

     get_rsps(xlk), get_rsps(xlc), 
     get_rsps(xlv), get_rsps(xlf), 
     get_rsps(xly), get_rsps(xlp), 
     get_rsps(xli), get_rsps(xlb),
     get_rsps(xle), get_rsps(xlu), 
     get_rsps(spy)
     )

filtered_values = array.from(

     filter(values.get(0)), filter(values.get(1)), 
     filter(values.get(2)), filter(values.get(3)),
     filter(values.get(4)), filter(values.get(5)),
     filter(values.get(6)), filter(values.get(7)), 
     filter(values.get(8)), filter(values.get(9)), 
     filter(values.get(10))

     )
max_alloc = filtered_values.sum()

alloc = array.from(

     filtered_values.get(0) / max_alloc, filtered_values.get(1) / max_alloc, 
     filtered_values.get(2) / max_alloc, filtered_values.get(3) / max_alloc, 
     filtered_values.get(4) / max_alloc, filtered_values.get(5) / max_alloc, 
     filtered_values.get(6) / max_alloc, filtered_values.get(7) / max_alloc, 
     filtered_values.get(8) / max_alloc, filtered_values.get(9) / max_alloc, 
     filtered_values.get(10) / max_alloc
     )

roc_sectors = array.from(
     ta.roc(xlk, 1) * alloc.get(0)[1], ta.roc(xlc, 1) * alloc.get(1)[1], 
     ta.roc(xlv, 1) * alloc.get(2)[1], ta.roc(xlf, 1) * alloc.get(3)[1], 
     ta.roc(xly, 1) * alloc.get(4)[1], ta.roc(xlp, 1) * alloc.get(5)[1], 
     ta.roc(xli, 1) * alloc.get(6)[1], ta.roc(xlb, 1) * alloc.get(7)[1],
     ta.roc(xle, 1) * alloc.get(8)[1], ta.roc(xlu, 1) * alloc.get(9)[1],
     ta.roc(spy, 1) * alloc.get(10)[1]
     )




//cash
use_cash = input.bool(false)
cash = input.int(100)



get_data2(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close)))
get_data3(string input) =>
    nz(L.deep_1d_cal(request.security(input, timeframe.period, close[13] * -1)))




rsps = array.from(

     math.avg(
         //benchmark
  
         get_data2("SPY * -1"),
         get_data2("XLK * -1"),
         get_data2("XLC * -1"),
         get_data2("XLV * -1"),
         get_data2("XLF * -1"),
         get_data2("XLY * -1"),
         get_data2("XLP * -1"),
         get_data2("XLI * -1"),
         get_data2("XLB * -1"),
         get_data2("XLE * -1"),
         get_data2("XLU * -1")) * 0.75,
 

     math.avg(
         get_data3("USDWCU + EURWCU + CNYWCU+ JPYWCU"),
         math.avg(get_data3("T10Y2Y"),
             get_data3("BAMLH0A0HYM2 * -1")),
         get_data3("(USGD + USM2 + USCBBS) * USDWCU")) * 0.25


     )

//plots

sectors_strength = rsps.sum() >= 0.2 ? 0 : filtered_values.avg()


color = color.rgb(212, 0, 0, 20)

f1 = plot(0, "midline", #ffffff, 2)
f2 = plot(sectors_strength, "Sectors tpi", color, 3)
fill(f1, f2, color)


col_out = sectors_strength > 0 ? 1 : 5
plot(col_out, "color", display = display.none)


f3 = plot(0, "midline", #ffffff)
f4 = plot(rsps.sum() <= 0 ? 0 : rsps.sum() * 0.5, "TPI", color.navy, 2,plot.style_line,true)
fill(f3, f4, color.new(color.navy, 20))


summe = (filter(rsps.sum()) * 0.5 + sectors_strength)

cash_alloc = filter(rsps.sum()) * 0.5 / summe

main_alloc = sectors_strength / summe


// Robustify main_roc calculation and perf update
main_roc = nz(roc_sectors.sum() * main_alloc, 0)

var float perf = 0.2
perf := perf * (1 + main_roc / 100)
plot(perf, "Portfolio Performance", color = cash_alloc >= sectors_strength ? color.blue : color.red, linewidth=2, force_overlay = true)




//===================================================
//plot rsps table

//table
var t = table.new(position.bottom_left, 40, 40, na, na, na, na, na, true)

if plot_table


//sector header
    t.cell(0, 2, "Sectors", text_color = #ffffff)
    t.merge_cells(0, 2, 2, 2)
    t.cell(0, 3, "Asset", text_color = #ffffff)
    t.cell(1, 3, "RSPS Value", text_color = #ffffff)
    t.cell(2, 3, " ", text_color = #000000)
    // Cash-Header hinzufügen, wenn benötigt
    if use_cash
        table.cell(t, 2, 3, "cash", text_color = #ffffff)
    else
        table.cell(t, 2, 3, " ", text_color = #ffffff)




//spacer
    t.cell(0, 1, "                ")
    t.cell(0, 12, "                ")


     //sector main table - jetzt mit Cash-Berechnungen in derselben Schleife
    for c = 0 to 10
        // Asset-Namen anzeigen
        table.cell(t, 0, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : names.get(c) : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Prozentuale Allokation anzeigen
        table.cell(t, 1, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(math.round(alloc.get(c) * main_alloc * 100, 2)) + "%" : na, 
         bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : values.get(c) <= 0.1 ? color.gray : color.red : na)

        // Cash-Wert berechnen und anzeigen, wenn aktiviert
        if use_cash
            float the_cash_plot = math.round(alloc.get(c) * main_alloc * cash, 2)
            table.cell(t, 2, c + 4, rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : str.tostring(the_cash_plot) : na, 
             bgcolor = na, text_color = rsps.sum() <= 0.2 ? values.get(c) <= -1 ? na :  values.get(c) <= 0.0 ? na : color.aqua : na)


    table.cell(t, 0, 15, "cash", 
             bgcolor = na,
             text_color = color.blue)

    // Prozentuale Allokation anzeigen
    table.cell(t, 1, 15, str.tostring(math.round(cash_alloc * 100, 2)) + "%", bgcolor = na, text_color =  color.blue)

    // Cash-Wert berechnen und anzeigen, wenn aktiviert
    if use_cash
        float the_cash_plot = math.round(cash_alloc * cash, 2),
        table.cell(t, 2, 15, str.tostring(the_cash_plot), text_color = color.blue)
